const SUPABASE_URL='https://iymhyxheggqsewpczgjl.supabase.co';
const SUPABASE_KEY='sb_publishable_Q8yb_Mw70jDkwld8YGQRRw_h-T5Rau2';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const $=id=>document.getElementById(id);let session=localStorage.getItem('driveiq_session')||'';let role=localStorage.getItem('driveiq_role')||'';let driver=null;let shotData=null;let ocrText='';let extraction='manual';let confidence=0;let gps=null;let currentJob=null;
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2400)}
async function api(body){let name,params;if(body.action==='login'){name='driveiq_login';params={p_code:body.code}}else if(body.action==='me'){name='driveiq_me';params={p_token:session}}else if(body.action==='save_settings'){name='driveiq_save_settings';params={p_token:session,p_vehicle:body.vehicle,p_hourly_target:body.hourly_target,p_mile_target:body.mile_target,p_cost_per_mile:body.cost_per_mile,p_wait_buffer:body.wait_buffer}}else if(body.action==='score_job'){name='driveiq_score_job';const p={...body};delete p.action;params={p_token:session,p_payload:p}}else if(body.action==='feedback'){name='driveiq_feedback';const p={...body};delete p.action;params={p_token:session,p_payload:p}}else if(body.action==='history'){name='driveiq_history';params={p_token:session}}else if(body.action==='admin_dashboard'){name='driveiq_admin_dashboard';params={p_token:session}}else{throw new Error('Unknown action')}const {data,error}=await db.rpc(name,params);if(error)throw new Error(error.message||'Request failed');return data}
function money(n){return '£'+Number(n||0).toFixed(2)}
function show(el){el.classList.remove('hidden')} function hide(el){el.classList.add('hidden')}
function setLoading(on,title='Working…',text=''){on?show($('loading')):hide($('loading'));$('loadTitle').textContent=title;$('loadText').textContent=text||'';if(!on)$('progressBar').style.width='0%'}
function showDriver(){hide($('loginScreen'));hide($('adminApp'));show($('driverApp'));$('driverLabel').textContent=(driver?.display_name||'PILOT DRIVER').toUpperCase();fillSettings();loadHistory()}
function showAdmin(){hide($('loginScreen'));hide($('driverApp'));show($('adminApp'));loadAdmin()}
function logout(){localStorage.removeItem('driveiq_session');localStorage.removeItem('driveiq_role');session='';role='';location.reload()}
$('loginBtn').onclick=async()=>{try{const code=$('accessCode').value.trim();if(!code)return toast('Enter your pilot access code');setLoading(true,'Signing in…','Opening the DRIVEIQ pilot');const j=await api({action:'login',code});session=j.token;role=j.role;driver=j.driver;localStorage.setItem('driveiq_session',session);localStorage.setItem('driveiq_role',role);role==='admin'?showAdmin():showDriver()}catch(e){toast(e.message)}finally{setLoading(false)}};
async function boot(){if(!session)return;try{const j=await api({action:'me'});role=j.role;driver=j.driver;role==='admin'?showAdmin():showDriver()}catch{logout()}}
$('shot').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{shotData=r.result;$('previewImg').src=shotData;show($('preview'));show($('readBtn'))};r.readAsDataURL(f)};
async function getGps(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};resolve(gps)},()=>resolve(null),{enableHighAccuracy:true,timeout:6500,maximumAge:20000})})}
function parseOCR(text){const clean=text.replace(/,/g,'.');const lower=clean.toLowerCase();let platform='Other';if(lower.includes('uber'))platform='Uber Eats';else if(lower.includes('deliveroo'))platform='Deliveroo';else if(lower.includes('just eat')||lower.includes('justeat'))platform='Just Eat';const pays=[...clean.matchAll(/£\s*([0-9]+(?:\.[0-9]{1,2})?)/g)].map(m=>Number(m[1])).filter(x=>x>0&&x<100);const dists=[...lower.matchAll(/([0-9]+(?:\.[0-9]+)?)\s*(?:mi|mile|miles)\b/g)].map(m=>Number(m[1])).filter(x=>x>0&&x<100);const mins=[...lower.matchAll(/([0-9]{1,3})\s*(?:min|mins|minute|minutes)\b/g)].map(m=>Number(m[1])).filter(x=>x>0&&x<180);const lines=clean.split(/\n+/).map(x=>x.trim()).filter(x=>x.length>2);let pickup='';for(const line of lines){const l=line.toLowerCase();if(/mcdonald|kfc|subway|burger king|starbucks|pizza|restaurant|cafe|café|grill|chicken|sushi|kebab|nando/.test(l)){pickup=line.slice(0,120);break}}const found=[pays.length,dists.length,mins.length].filter(Boolean).length;return{platform,pay:pays[0]||'',distance:dists[0]||'',minutes:mins[0]||'',pickup,confidence:Math.round(found/3*100)}}
async function scoreCurrentOffer(){const pay=Number($('pay').value),dist=Number($('distance').value),mins=Number($('minutes').value);if(!(pay>0)||!(mins>0))return false;setLoading(true,'Scoring job…','Checking your targets and estimated net return');const j=await api({action:'score_job',platform:$('platform').value,offer_pay:pay,displayed_distance:dist||0,estimated_time:mins,pickup:$('pickup').value,dropoff:$('dropoff').value,distance_scope:$('scope').value,pickup_distance:Number($('pickupMiles').value)||0,pickup_time:Number($('pickupMins').value)||0,include_wait:$('includeWait').checked,include_pickup:$('scope').value!=='total'&&(Number($('pickupMiles').value)||0)>0,gps_lat:gps?.lat,gps_lng:gps?.lng,gps_accuracy:gps?.accuracy,extraction_method:extraction,extraction_confidence:confidence,ocr_text:null});currentJob=j.job;renderResult(j.score);hide($('scorePage'));hide($('confirmPage'));hide($('historyPage'));hide($('settingsPage'));show($('resultPage'));await loadHistory();return true}
$('readBtn').onclick=async()=>{if(!shotData)return;setLoading(true,'Reading your offer…','OCR is running on this phone. The screenshot is not uploaded.');try{const gpsPromise=getGps();if(!window.Tesseract)throw new Error('OCR engine could not load');const worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.progress)$('progressBar').style.width=Math.round(m.progress*100)+'%'}});const ret=await worker.recognize(shotData);await worker.terminate();ocrText=ret.data.text||'';const p=parseOCR(ocrText);$('platform').value=p.platform;$('pay').value=p.pay;$('distance').value=p.distance;$('minutes').value=p.minutes;$('pickup').value=p.pickup;confidence=p.confidence;extraction='ocr';gps=await gpsPromise;const canAutoScore=confidence===100&&Number(p.pay)>0&&Number(p.distance)>0&&Number(p.minutes)>0;if(canAutoScore){$('progressBar').style.width='100%';await scoreCurrentOffer()}else{openConfirm();$('ocrStatus').className='status warn';$('ocrStatus').textContent='DRIVEIQ is not fully confident in this screenshot. Check the highlighted job details before scoring.'}}catch(e){toast('OCR could not read it — enter the offer manually');extraction='manual';confidence=0;gps=await getGps();openConfirm()}finally{setLoading(false)}};
$('manualBtn').onclick=async()=>{extraction='manual';ocrText='';confidence=0;gps=await getGps();openConfirm()};
function openConfirm(){hide($('scorePage'));hide($('resultPage'));hide($('historyPage'));hide($('settingsPage'));show($('confirmPage'));$('gpsStatus').className='status '+(gps?'good':'warn');$('gpsStatus').textContent=gps?`Location captured • accuracy about ${Math.round(gps.accuracy)}m`:'Location unavailable • DRIVEIQ can still score from the offer details.'}
$('scope').onchange=()=>{const v=$('scope').value;v==='total'?hide($('pickupExtra')):show($('pickupExtra'))};
$('backBtn').onclick=()=>switchPage('score');
$('scoreBtn').onclick=async()=>{try{const ok=await scoreCurrentOffer();if(!ok)return toast('Pay and estimated minutes are required')}catch(e){toast(e.message)}finally{setLoading(false)}};
function renderResult(s){const c=$('resultCard');c.className='panel result '+(s.verdict==='TAKE'?'takeR':s.verdict==='BORDERLINE'?'borderR':'skipR');$('verdictTitle').textContent=s.verdict==='TAKE'?'TAKE IT':s.verdict==='BORDERLINE'?'BORDERLINE':'SKIP IT';$('verdictSub').textContent=s.verdict==='TAKE'?'This offer clears both of your targets.':s.verdict==='BORDERLINE'?'Close enough to consider, but watch the weak metric.':'This offer falls too far below your targets.';$('rate').textContent=money(s.netHourly)+'/hr';$('perMile').textContent=money(s.netPerMile);$('net').textContent=money(s.netProfit);$('totalMiles').textContent=Number(s.totalDistance).toFixed(1);$('reasonList').innerHTML=s.reasons.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')}
document.querySelectorAll('.feedbackButtons button').forEach(b=>b.onclick=async()=>{if(!currentJob)return;try{await api({action:'feedback',job_id:currentJob.id,driver_action:b.dataset.action});toast('Result saved');await loadHistory()}catch(e){toast(e.message)}});$('againBtn').onclick=()=>{resetScore();switchPage('score')};
function resetScore(){shotData=null;ocrText='';confidence=0;gps=null;currentJob=null;$('shot').value='';hide($('preview'));hide($('readBtn'));['pay','distance','minutes','pickup','dropoff','pickupMiles','pickupMins'].forEach(id=>$(id).value='')}
async function loadHistory(){try{const j=await api({action:'history'});renderHistory(j.jobs||[])}catch(e){}}
function renderHistory(jobs){const html=jobs.length?jobs.map(j=>{const f=j.feedback;const actual=f?.actual_minutes?` • actual ${f.actual_minutes}m`:'';return `<div class="historyItem"><div class="historyMain"><b>${escapeHtml(j.platform)} • ${money(j.offer_pay)} • ${Number(j.total_distance).toFixed(1)}mi</b><small>${escapeHtml(j.pickup||'Pickup not recorded')} • ${new Date(j.created_at).toLocaleString()}${actual}</small>${f?.driver_action==='accepted'&&!f.actual_minutes?`<button class="linkbtn" onclick="addActual('${j.id}',${Number(j.offer_pay)})">ADD ACTUAL RESULT</button>`:''}</div><div class="historyRight"><span class="vtag v${j.verdict}">${j.verdict}</span><small style="display:block;color:#788eaf;margin-top:5px">${money(j.net_hourly)}/hr</small></div></div>`}).join(''):'<div class="helper">No jobs scored yet.</div>';$('historyList').innerHTML=html;$('recentList').innerHTML=jobs.length?html.split('</div></div>').slice(0,3).join('</div></div>')+'</div></div>':'<div class="helper">No jobs scored yet.</div>'}
window.addActual=async(id,offer)=>{const mins=prompt('Actual minutes from accept to completed?');if(!mins)return;const earnings=prompt('Actual earnings for this job (£)?',String(offer));const miles=prompt('Actual miles if known (optional):','');const delay=prompt('Main delay reason? e.g. restaurant wait / traffic / parking / none','none');try{await api({action:'feedback',job_id:id,driver_action:'accepted',actual_minutes:Number(mins),actual_earnings:Number(earnings||offer),actual_miles:miles===''?null:Number(miles),delay_reason:delay});toast('Actual result saved');loadHistory()}catch(e){toast(e.message)}};
function fillSettings(){if(!driver)return;$('vehicle').value=driver.vehicle;$('hourTarget').value=driver.hourly_target;$('mileTarget').value=driver.mile_target;$('costMile').value=driver.cost_per_mile;$('waitBuffer').value=driver.wait_buffer}
$('saveSettings').onclick=async()=>{try{const j=await api({action:'save_settings',vehicle:$('vehicle').value,hourly_target:Number($('hourTarget').value),mile_target:Number($('mileTarget').value),cost_per_mile:Number($('costMile').value),wait_buffer:Number($('waitBuffer').value)});driver=j.driver;toast('Targets saved')}catch(e){toast(e.message)}};$('logoutDriver').onclick=logout;$('logoutAdmin').onclick=logout;
function switchPage(p){['score','confirm','result','history','settings'].forEach(x=>hide($(x+'Page')));if(p==='score')show($('scorePage'));else show($(p+'Page'));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='history')loadHistory();if(p==='settings')fillSettings()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
async function loadAdmin(){try{setLoading(true,'Loading pilot data…','Building the live admin view');const j=await api({action:'admin_dashboard'});const jobs=j.jobs||[],drivers=j.drivers||[];const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const actualRates=jobs.filter(x=>x.feedback?.actual_minutes&&x.feedback?.actual_earnings).map(x=>(Number(x.feedback.actual_earnings)/Number(x.feedback.actual_minutes))*60);const timeErrors=jobs.filter(x=>x.feedback?.actual_minutes).map(x=>Math.abs(Number(x.feedback.actual_minutes)-Number(x.total_time)));const s={jobs:jobs.length,drivers:drivers.length,take:jobs.filter(x=>x.verdict==='TAKE').length,borderline:jobs.filter(x=>x.verdict==='BORDERLINE').length,skip:jobs.filter(x=>x.verdict==='SKIP').length,avg_predicted_hourly:avg(jobs.map(x=>Number(x.net_hourly))),avg_actual_hourly:avg(actualRates),avg_time_error_mins:avg(timeErrors)};$('aJobs').textContent=s.jobs;$('aDrivers').textContent=s.drivers;$('aPred').textContent=money(s.avg_predicted_hourly);$('aActual').textContent=money(s.avg_actual_hourly);$('aTake').textContent=s.take;$('aBorder').textContent=s.borderline;$('aSkip').textContent=s.skip;$('aError').textContent=(s.avg_time_error_mins||0).toFixed(1)+'m';$('adminRows').innerHTML=jobs.map(x=>{const f=x.feedback;const actual=f?.actual_minutes&&f?.actual_earnings?money((Number(f.actual_earnings)/Number(f.actual_minutes))*60)+'/hr':f?.driver_action||'—';return `<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${escapeHtml(x.driver_name||'Driver')}</td><td>${escapeHtml(x.platform)}</td><td>${money(x.offer_pay)}</td><td>${Number(x.total_distance).toFixed(1)}</td><td><span class="vtag v${x.verdict}">${x.verdict}</span></td><td>${money(x.net_hourly)}</td><td>${actual}</td><td>${escapeHtml(x.pickup||'—')}</td></tr>`}).join('');renderHotspots(jobs)}catch(e){toast(e.message)}finally{setLoading(false)}}
function renderHotspots(jobs){const m={};jobs.forEach(j=>{const p=(j.pickup||'').trim();if(!p)return;const f=j.feedback;if(!m[p])m[p]={n:0,delays:0,total:0};m[p].n++;if(f?.actual_minutes){m[p].delays++;m[p].total+=Math.max(0,Number(f.actual_minutes)-Number(j.total_time))}});const a=Object.entries(m).map(([name,v])=>({name,...v,avg:v.delays?v.total/v.delays:0})).sort((a,b)=>b.n-a.n).slice(0,8);$('hotspots').innerHTML=a.length?a.map(x=>`<div class="hotspot"><div><b>${escapeHtml(x.name)}</b><small>${x.n} scored jobs</small></div><div style="text-align:right"><b>${x.avg>0?'+'+x.avg.toFixed(1)+'m':'—'}</b><small>avg observed delay</small></div></div>`).join(''):'<div class="helper">Waiting for pickup data.</div>'}
$('refreshAdmin').onclick=loadAdmin;
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
boot();