(()=>{
const AUTH='pressed_auth_v2',LEGACY='pressed_auth_v1',PENDING='pressed_pending_booking_v1';
const SUPA='https://iymhyxheggqsewpczgjl.supabase.co',KEY='sb_publishable_Q8yb_Mw70jDkwld8YGQRRw_h-T5Rau2';
const PRICE={small:27.99,large:37.99,suit:25,express:49.99},LABEL={small:'Small Bag',large:'Large Bag',suit:'Suit Service',express:'Same-Day Express'};
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>'£'+Number(n||0).toFixed(2);
const getAuth=()=>{try{return JSON.parse(localStorage.getItem(AUTH)||localStorage.getItem(LEGACY)||'null')}catch(e){return null}};
function saveAuth(d){const s=d?.session||d;if(!s?.access_token)return null;const x={access_token:s.access_token,refresh_token:s.refresh_token||'',user:d.user||s.user||null};localStorage.setItem(AUTH,JSON.stringify(x));localStorage.removeItem(LEGACY);return x}
const clearAuth=()=>{localStorage.removeItem(AUTH);localStorage.removeItem(LEGACY)};
async function auth(path,body){const r=await fetch(SUPA+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||'Account request failed.');return d}
async function refresh(){const a=getAuth();if(!a?.refresh_token)return null;try{return saveAuth(await auth('/auth/v1/token?grant_type=refresh_token',{refresh_token:a.refresh_token}))}catch(e){clearAuth();return null}}
async function api(path,opt={},retry=true){let a=getAuth();if(!a?.access_token)throw new Error('Please sign in to My Presse’d first.');const headers={apikey:KEY,Authorization:'Bearer '+a.access_token,'Content-Type':'application/json',...(opt.headers||{})};let r=await fetch(SUPA+path,{...opt,headers});if(r.status===401&&retry&&await refresh())return api(path,opt,false);let d=null,t=await r.text();if(t){try{d=JSON.parse(t)}catch(e){d=t}}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||d?.hint||'Could not load your account.');return d}
async function user(){try{return await api('/auth/v1/user',{method:'GET'})}catch(e){return null}}
async function login(email,password){const d=await auth('/auth/v1/token?grant_type=password',{email,password});saveAuth(d);return d.user||d.session?.user||await user()}
async function signup(email,password,name){const d=await auth('/auth/v1/signup',{email,password,data:{full_name:name,brand:'pressed_db'}});if(d.access_token||d.session?.access_token)saveAuth(d);return d}
async function rest(table,{method='GET',query='',body,prefer}={}){const headers={};if(prefer)headers.Prefer=prefer;return api(`/rest/v1/${table}${query?'?'+query:''}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)})}
async function profile(u){const d=await rest('pressed_customers',{query:`select=*&user_id=eq.${encodeURIComponent(u.id)}&limit=1`});return d?.[0]||null}
async function bookings(){const d=await rest('pressed_bookings',{query:'select=*&order=created_at.desc'});return Array.isArray(d)?d:[]}
async function saveProfile(u,p){const row={user_id:u.id,email:(u.email||p.email).toLowerCase(),full_name:p.name,phone:p.phone||null,address1:p.address1||null,address2:p.address2||null,postcode:p.postcode||null,access_notes:p.accessNotes||null,preferred_service:window.PRESSED_SERVICE||'small',updated_at:new Date().toISOString()};return rest('pressed_customers',{method:'POST',query:'on_conflict=user_id',body:row,prefer:'resolution=merge-duplicates,return=representation'})}
async function saveBooking(u,b){const row={id:b.id,user_id:u.id,ref:b.ref,service:b.service,service_label:b.serviceLabel,price:b.price,customer_name:b.name,customer_email:b.email,customer_phone:b.phone||null,address1:b.address1||null,address2:b.address2||null,postcode:b.postcode||null,item_count:b.itemCount,extra_shirts:b.extraShirts,collection_date:b.collectionDate,collection_slot:b.collectionSlot,return_date:b.returnDate,return_slot:b.returnSlot,access_notes:b.accessNotes||null,instructions:b.instructions||null,status:'Booking requested',payment_status:'Payment due before return'};return rest('pressed_bookings',{method:'POST',body:row,prefer:'return=representation'})}
const pending=()=>{try{return JSON.parse(localStorage.getItem(PENDING)||'null')}catch(e){return null}};
async function finishPending(u){const p=pending();if(!p||p.email?.toLowerCase()!==u.email?.toLowerCase())return false;try{await saveProfile(u,p.profile);await saveBooking(u,p.booking);localStorage.removeItem(PENDING);localStorage.setItem('pressed_last_ref',p.booking.ref);return true}catch(e){return false}}
function fromForm(f){const g=n=>String(f.get(n)||'').trim(),email=g('email').toLowerCase(),service=window.PRESSED_SERVICE||'small',shirts=Number(f.get('extraShirts')||0),name=g('name');return {email,profile:{email,name,phone:g('phone'),address1:g('address1'),address2:g('address2'),postcode:g('postcode').toUpperCase(),accessNotes:g('accessNotes')},booking:{id:crypto.randomUUID(),ref:`PDB-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,service,serviceLabel:LABEL[service],price:PRICE[service]+((service==='small'||service==='large')?shirts*3:0),name,email,phone:g('phone'),address1:g('address1'),address2:g('address2'),postcode:g('postcode').toUpperCase(),itemCount:Number(f.get('itemCount')||0),extraShirts:shirts,collectionDate:g('collectionDate'),collectionSlot:window.PRESSED_SLOT||'',returnDate:g('returnDate'),returnSlot:g('returnSlot'),accessNotes:g('accessNotes'),instructions:g('instructions')}}}
function confirm(b,msg){const box=$('#confirmation');if(!box)return;box.classList.add('show');[['#confirmRef',b.ref],['#confirmService',b.serviceLabel],['#confirmPrice',money(b.price)],['#confirmWhen',`${b.collectionDate} · ${b.collectionSlot}`],['#confirmAccount',msg]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v});box.scrollIntoView({behavior:'smooth',block:'center'})}
async function bookingSubmit(form){const fd=new FormData(form),x=fromForm(fd),pass=String(fd.get('password')||''),mode=window.PRESSED_ACCOUNT_MODE||'new',btn=form.querySelector('button[type=submit]');if(!x.booking.collectionSlot)return alert('Please choose an available collection window.');if(mode!=='signedin'&&pass.length<8)return alert('Please use a password of at least 8 characters.');const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent=mode==='new'?'CREATING ACCOUNT...':'SAVING BOOKING...'}try{let u=await user();if(!u){if(mode==='new'){let d;try{d=await signup(x.email,pass,x.profile.name)}catch(e){if(/already|registered|exists/i.test(e.message))throw new Error('That email already has a My Presse’d account. Choose “I already have an account” and sign in.');throw e}u=d.user||d.session?.user||null;if(!d.access_token&&!d.session?.access_token){localStorage.setItem(PENDING,JSON.stringify({...x,createdAt:new Date().toISOString()}));localStorage.setItem('pressed_last_email',x.email);localStorage.setItem('pressed_last_ref',x.booking.ref);confirm(x.booking,'Your My Presse’d account has been created. Verify your email, then sign in. Your first booking will be added to your account when you sign in on this device.');return}}else u=await login(x.email,pass)}if(!u)u=await user();if(!u)throw new Error('Please sign in to complete this booking.');if(u.email?.toLowerCase()!==x.email)throw new Error(`You are signed in as ${u.email}. Log out before using another email.`);await saveProfile(u,x.profile);await saveBooking(u,x.booking);localStorage.setItem('pressed_last_email',x.email);localStorage.setItem('pressed_last_ref',x.booking.ref);confirm(x.booking,'Your booking is saved to My Presse’d. Sign in from any device to view bookings and track status.')}catch(e){alert(e.message||'Could not save booking.')}finally{if(btn){btn.disabled=false;btn.textContent=mode==='signedin'?'REQUEST BOOKING':old}}}
const stages=['Booking requested','Confirmed','Collected','Pressing','Ready for return','Completed'];
function card(b){let i=Math.max(0,stages.indexOf(b.status));return `<div class="bookingcard"><div class="top"><div><span class="pill">${esc(b.status)}</span><h3 style="margin:10px 0 4px">${esc(b.service_label)}</h3><div class="muted">${esc(b.ref)}</div></div><strong style="font-size:22px;color:#c9a24d">${money(b.price)}</strong></div><div class="statusline">${stages.map((_,n)=>`<i class="${n<=i?'on':''}"></i>`).join('')}</div><div class="summary-row"><span>Collection</span><b>${esc(b.collection_date)} · ${esc(b.collection_slot)}</b></div><div class="summary-row"><span>Return</span><b>${esc(b.return_date)} · ${esc(b.return_slot)}</b></div><div class="summary-row"><span>Payment</span><b>${esc(b.payment_status)}</b></div></div>`}
async function showAccount(u){const login=$('#accountLoginPanel'),dash=$('#accountDashboard');if(login)login.style.display='none';if(dash)dash.style.display='block';$('#accountUserEmail')&&($('#accountUserEmail').textContent=u.email||'—');let p=null,bs=[];try{p=await profile(u);bs=await bookings()}catch(e){};$('#savedName')&&($('#savedName').textContent=p?.full_name||u.user_metadata?.full_name||'—');$('#savedPhone')&&($('#savedPhone').textContent=p?.phone||'—');$('#savedAddress')&&($('#savedAddress').textContent=[p?.address1,p?.address2,p?.postcode].filter(Boolean).join(', ')||'—');const out=$('#myBookings');if(out)out.innerHTML=bs.length?bs.map(card).join(''):'<div class="empty">No bookings yet. Your bookings will appear here.</div>'}
async function accountLogin(form){const email=$('#loginEmail')?.value.trim().toLowerCase(),pass=$('#loginPassword')?.value||'',msg=$('#loginMsg');try{const u=await login(email,pass);localStorage.setItem('pressed_last_email',email);const done=await finishPending(u);if(msg)msg.textContent=done?'Your first booking has now been added to your account.':'';await showAccount(u)}catch(e){if(msg)msg.textContent=e.message||'Sign-in failed.'}}
async function track(form){const out=$('#trackResult'),ref=$('#trackRef')?.value.trim().toUpperCase();if(!out)return;const u=await user();if(!u){out.innerHTML='<div class="empty">Tracking is private. <a href="/pressed/account">Sign in to My Presse’d</a> to track your booking.</div>';return}try{const d=await rest('pressed_bookings',{query:`select=*&ref=eq.${encodeURIComponent(ref)}&limit=1`});out.innerHTML=d?.[0]?card(d[0]):'<div class="empty">That booking reference is not in your account.</div>'}catch(e){out.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function init(){
 const u=await user();
 if($('#accountLoginPanel')&&u){await finishPending(u);await showAccount(u)}
 if($('#bookingForm')&&u){window.PRESSED_ACCOUNT_MODE='signedin';const e=$('#bookingForm [name=email]');if(e){e.value=u.email;e.readOnly=true}const pw=$('#bookingPassword');if(pw){pw.required=false;pw.closest('.field').style.display='none'}const modes=$('[data-account-mode]')?.closest('.actions');if(modes)modes.style.display='none';const c=$('#accountModeCopy');if(c)c.innerHTML=`<b>Signed in as ${esc(u.email)}.</b> This booking will be saved to your account.`;const b=$('#bookingForm button[type=submit]');if(b)b.textContent='REQUEST BOOKING';try{const p=await profile(u),f=$('#bookingForm');if(p&&f){for(const [n,v] of Object.entries({name:p.full_name,phone:p.phone,address1:p.address1,address2:p.address2,postcode:p.postcode,accessNotes:p.access_notes})){const el=f.elements.namedItem(n);if(el&&!el.value&&v)el.value=v}}}catch(e){}}
}
document.addEventListener('submit',e=>{if(e.target?.id==='bookingForm'){e.preventDefault();e.stopImmediatePropagation();bookingSubmit(e.target)}else if(e.target?.id==='accountLoginForm'){e.preventDefault();e.stopImmediatePropagation();accountLogin(e.target)}else if(e.target?.id==='trackForm'){e.preventDefault();e.stopImmediatePropagation();track(e.target)}},true);
document.addEventListener('click',e=>{if(e.target?.id==='logoutBtn'){e.preventDefault();e.stopImmediatePropagation();clearAuth();location.href='/pressed/account'}},true);
document.addEventListener('DOMContentLoaded',init);
})();