(()=>{
const SUPA='https://iymhyxheggqsewpczgjl.supabase.co',KEY='sb_publishable_Q8yb_Mw70jDkwld8YGQRRw_h-T5Rau2',AUTH='pressed_admin_auth_v1';
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let started=false,lastUnread=new Set();
const auth=()=>{try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch(e){return null}};
async function refresh(){const a=auth();if(!a?.refresh_token)return null;const r=await fetch(SUPA+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a.refresh_token})});if(!r.ok)return null;const d=await r.json(),x={access_token:d.access_token,refresh_token:d.refresh_token||a.refresh_token,user:d.user||a.user};localStorage.setItem(AUTH,JSON.stringify(x));return x}
async function api(path,opt={},retry=true){let a=auth();if(!a?.access_token)throw new Error('Admin sign-in required.');const headers={apikey:KEY,Authorization:'Bearer '+a.access_token,'Content-Type':'application/json',...(opt.headers||{})};let r=await fetch(SUPA+path,{...opt,headers});if(r.status===401&&retry&&await refresh())return api(path,opt,false);let t=await r.text(),d=t;try{d=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw new Error(d?.message||d?.error||d?.hint||'Request failed.');return d}
const iso=d=>d.toISOString().slice(0,10),today=()=>iso(new Date());
function dayPlus(n){const d=new Date();d.setDate(d.getDate()+n);return iso(d)}
function setCaps(c=4,r=4,express=true,note=''){if($('#collectionCap'))$('#collectionCap').value=String(c);if($('#returnCap'))$('#returnCap').value=String(r);if($('#expressEnabled'))$('#expressEnabled').checked=express;if($('#capacityNote'))$('#capacityNote').value=note||''}
async function loadEditor(){const date=$('#capacityDate')?.value;if(!date)return;const rows=await api('/rest/v1/pressed_capacity_overrides?select=*&service_date=eq.'+encodeURIComponent(date));const x=rows?.[0];if(x){setCaps(x.collection_capacity,x.return_capacity,x.express_enabled,x.note);$('#capacityPreset').value=(x.collection_capacity===4&&x.return_capacity===4)?'open':(x.collection_capacity===2&&x.return_capacity===2)?'reduced':(x.collection_capacity===0&&x.return_capacity===0)?'closed':'custom';$('#capacityState').textContent='Custom capacity saved for this date.'}else{$('#capacityPreset').value='open';setCaps();$('#capacityState').textContent='Using normal launch capacity: 4 collections / 4 returns.'}}
async function saveCapacity(){const a=auth(),date=$('#capacityDate').value,c=Number($('#collectionCap').value),r=Number($('#returnCap').value),row={service_date:date,collection_capacity:c,return_capacity:r,express_enabled:$('#expressEnabled').checked,note:$('#capacityNote').value.trim()||null,updated_by:a?.user?.id||null,updated_at:new Date().toISOString()};const btn=$('#saveCapacity');btn.disabled=true;try{await api('/rest/v1/pressed_capacity_overrides?on_conflict=service_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});$('#capacityState').textContent='Saved — customer availability is updated live.';await loadCalendar()}catch(e){alert(e.message)}finally{btn.disabled=false}}
async function resetCapacity(){const date=$('#capacityDate').value;if(!confirm('Restore normal 4-in / 4-out capacity for '+date+'?'))return;try{await api('/rest/v1/pressed_capacity_overrides?service_date=eq.'+encodeURIComponent(date),{method:'DELETE',headers:{Prefer:'return=minimal'}});await loadEditor();await loadCalendar()}catch(e){alert(e.message)}}
async function loadCalendar(){const start=today(),end=dayPlus(13);const [ovs,bs]=await Promise.all([api('/rest/v1/pressed_capacity_overrides?select=*&service_date=gte.'+start+'&service_date=lte.'+end+'&order=service_date.asc'),api('/rest/v1/pressed_bookings?select=collection_date,return_date,status,service&or=(collection_date.gte.'+start+',return_date.gte.'+start+')')]);const map=new Map((ovs||[]).map(x=>[x.service_date,x]));const out=$('#capacityDays');if(!out)return;out.innerHTML=Array.from({length:14},(_,i)=>{const d=dayPlus(i),o=map.get(d),cc=o?.collection_capacity??4,rc=o?.return_capacity??4,cu=(bs||[]).filter(b=>b.status!=='Cancelled'&&b.collection_date===d).length,ru=(bs||[]).filter(b=>b.status!=='Cancelled'&&b.return_date===d).length,label=cc===0&&rc===0?'CLOSED':(cc<4||rc<4?'REDUCED':'OPEN');return `<button type="button" class="capacity-day ${label==='CLOSED'?'closed':''}" data-date="${d}"><b>${new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</b><span>${label}</span><small>Collect ${cu}/${cc} · Return ${ru}/${rc}${o?.express_enabled===false?' · Express off':''}</small></button>`}).join('');out.querySelectorAll('[data-date]').forEach(b=>b.onclick=async()=>{$('#capacityDate').value=b.dataset.date;await loadEditor();$('#capacityDate').scrollIntoView({behavior:'smooth',block:'center'})})}
async function loadAlerts(first=false){const rows=await api('/rest/v1/pressed_admin_notifications?select=*&order=created_at.desc&limit=20'),unread=(rows||[]).filter(x=>!x.is_read);const badge=$('#alertCount');if(badge)badge.textContent=String(unread.length);const out=$('#adminAlerts');if(out)out.innerHTML=(rows||[]).length?(rows||[]).map(n=>`<div class="alert-row ${n.is_read?'':'unread'}"><div><b>${esc(n.message)}</b><small>${new Date(n.created_at).toLocaleString('en-GB')}</small></div><span>${n.is_read?'READ':'NEW'}</span></div>`).join(''):'<div class="empty">No booking alerts yet.</div>';if(!first&&Notification?.permission==='granted'){unread.filter(n=>!lastUnread.has(n.id)).forEach(n=>new Notification('New Presse’d booking',{body:n.message}))}lastUnread=new Set(unread.map(n=>n.id))}
async function markRead(){try{await api('/rest/v1/pressed_admin_notifications?is_read=eq.false',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_read:true,read_at:new Date().toISOString()})});await loadAlerts(true)}catch(e){alert(e.message)}}
async function browserAlerts(){if(!('Notification'in window))return alert('Browser notifications are not supported on this device.');const p=await Notification.requestPermission();$('#browserAlertState').textContent=p==='granted'?'Browser alerts enabled while this browser allows notifications.':'Browser alerts were not enabled.'}
function fixExpress(){const e=$('#mExpress');if(e&&/\/2$/.test(e.textContent))e.textContent=e.textContent.replace(/\/2$/,'/1')}
async function start(){if(started||!auth()||getComputedStyle($('#adminBoard')).display==='none')return;started=true;$('#capacityDate').value=today();await Promise.allSettled([loadEditor(),loadCalendar(),loadAlerts(true)]);fixExpress();new MutationObserver(fixExpress).observe($('#mExpress'),{childList:true,characterData:true,subtree:true});setInterval(()=>loadAlerts(false).catch(()=>{}),30000)}
document.addEventListener('DOMContentLoaded',()=>{$('#capacityPreset')?.addEventListener('change',e=>{if(e.target.value==='open')setCaps(4,4,true,$('#capacityNote').value);if(e.target.value==='reduced')setCaps(2,2,true,$('#capacityNote').value);if(e.target.value==='closed')setCaps(0,0,false,$('#capacityNote').value)});$('#capacityDate')?.addEventListener('change',()=>loadEditor().catch(e=>alert(e.message)));$('#saveCapacity')?.addEventListener('click',saveCapacity);$('#resetCapacity')?.addEventListener('click',resetCapacity);$('#markAlertsRead')?.addEventListener('click',markRead);$('#enableBrowserAlerts')?.addEventListener('click',browserAlerts);$('#refreshBoard')?.addEventListener('click',()=>Promise.allSettled([loadCalendar(),loadAlerts(true)]));let tries=0;const t=setInterval(()=>{start().catch(()=>{});if(started||++tries>120)clearInterval(t)},500)});
})();