(()=>{
const SUPA='https://iymhyxheggqsewpczgjl.supabase.co',KEY='sb_publishable_Q8yb_Mw70jDkwld8YGQRRw_h-T5Rau2',AUTH='pressed_admin_auth_v1';
const stages=['Booking requested','Confirmed','Collected','Pressing','Ready for return','Completed','Cancelled'];
const $=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>'£'+Number(n||0).toFixed(2);
let cache=[];
const getAuth=()=>{try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch(e){return null}};
function saveAuth(d){const s=d?.session||d;if(!s?.access_token)return null;const x={access_token:s.access_token,refresh_token:s.refresh_token||'',user:d.user||s.user||null};localStorage.setItem(AUTH,JSON.stringify(x));return x}
const clearAuth=()=>localStorage.removeItem(AUTH);
async function auth(path,body){const r=await fetch(SUPA+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||'Sign-in failed.');return d}
async function refresh(){const a=getAuth();if(!a?.refresh_token)return null;try{return saveAuth(await auth('/auth/v1/token?grant_type=refresh_token',{refresh_token:a.refresh_token}))}catch(e){clearAuth();return null}}
async function api(path,opt={},retry=true){let a=getAuth();if(!a?.access_token)throw new Error('Please sign in.');const headers={apikey:KEY,Authorization:'Bearer '+a.access_token,'Content-Type':'application/json',...(opt.headers||{})};let r=await fetch(SUPA+path,{...opt,headers});if(r.status===401&&retry&&await refresh())return api(path,opt,false);let d=null,t=await r.text();if(t){try{d=JSON.parse(t)}catch(e){d=t}}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||d?.hint||'Request failed.');return d}
async function login(email,password){const d=await auth('/auth/v1/token?grant_type=password',{email,password});saveAuth(d);if(!await isAdmin()){clearAuth();throw new Error('This account does not have Presse’d admin access.')}return d}
async function isAdmin(){try{return (await api('/rest/v1/rpc/is_vett_admin',{method:'POST',body:'{}'}))===true}catch(e){return false}}
async function load(){cache=await api('/rest/v1/pressed_bookings?select=*&order=created_at.desc',{method:'GET'});render()}
function metrics(){const t=new Date().toISOString().slice(0,10),active=cache.filter(x=>x.status!=='Cancelled');$('#mToday').textContent=active.filter(x=>x.collection_date===t).length;$('#mPending').textContent=active.filter(x=>x.status==='Booking requested').length;$('#mExpress').textContent=active.filter(x=>x.collection_date===t&&x.service==='express').length+'/2';$('#mValue').textContent=money(active.reduce((a,x)=>a+Number(x.price||0),0))}
function render(){metrics();const out=$('#adminBookings'),filter=$('#statusFilter')?.value||'all';let list=cache;if(filter!=='all')list=list.filter(x=>x.status===filter);if(!list.length){out.innerHTML='<div class="empty">No bookings in this view yet.</div>';return}out.innerHTML=list.map(b=>`<div class="bookingcard" data-id="${esc(b.id)}"><div class="top"><div><span class="pill">${esc(b.status)}</span><h3 style="margin:10px 0 3px">${esc(b.customer_name)} · ${esc(b.service_label)}</h3><div class="muted">${esc(b.ref)} · ${esc(b.customer_email)} · ${esc(b.customer_phone||'')}</div></div><strong style="font-size:22px;color:#c9a24d">${money(b.price)}</strong></div><div class="grid2" style="margin-top:12px"><div><div class="summary-row"><span>Collect</span><b>${esc(b.collection_date)} · ${esc(b.collection_slot)}</b></div><div class="summary-row"><span>Return</span><b>${esc(b.return_date)} · ${esc(b.return_slot)}</b></div><div class="summary-row"><span>Items</span><b>${esc(b.item_count||'—')}</b></div></div><div><div class="summary-row"><span>Address</span><b>${esc([b.address1,b.address2,b.postcode].filter(Boolean).join(' '))}</b></div><div class="summary-row"><span>Payment</span><b>${esc(b.payment_status)}</b></div><div class="summary-row"><span>Notes</span><b>${esc(b.instructions||b.access_notes||'—')}</b></div></div></div><div class="grid2" style="margin-top:14px"><div class="field" style="margin:0"><label>Booking status</label><select class="statusSelect" data-id="${esc(b.id)}">${stages.map(s=>`<option ${s===b.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="field" style="margin:0"><label>Payment</label><select class="paySelect" data-id="${esc(b.id)}"><option ${b.payment_status==='Payment due before return'?'selected':''}>Payment due before return</option><option ${b.payment_status==='Paid'?'selected':''}>Paid</option><option ${b.payment_status==='Refunded'?'selected':''}>Refunded</option></select></div></div></div>`).join('');qsa('.statusSelect').forEach(el=>el.onchange=()=>update(el.dataset.id,{status:el.value}));qsa('.paySelect').forEach(el=>el.onchange=()=>update(el.dataset.id,{payment_status:el.value}))}
async function update(id,changes){const el=$(`[data-id="${CSS.escape(id)}"]`);if(el)el.style.opacity='.55';try{await api('/rest/v1/pressed_bookings?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...changes,updated_at:new Date().toISOString()})});const x=cache.find(v=>v.id===id);if(x)Object.assign(x,changes);render()}catch(e){alert(e.message);if(el)el.style.opacity='1'}}
async function showBoard(){if(!await isAdmin()){clearAuth();showLogin('Your session does not have admin access.');return}$('#adminLoginPanel').style.display='none';$('#adminBoard').style.display='block';await load()}
function showLogin(msg=''){$('#adminLoginPanel').style.display='block';$('#adminBoard').style.display='none';$('#adminLoginMsg').textContent=msg}
async function submitLogin(e){e.preventDefault();const btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='SIGNING IN...';try{await login($('#adminEmail').value.trim().toLowerCase(),$('#adminPassword').value);$('#adminLoginMsg').textContent='';await showBoard()}catch(err){showLogin(err.message)}finally{btn.disabled=false;btn.textContent='SIGN IN TO OWNER BOARD'}}
function logout(){clearAuth();location.href='/pressed/admin'}
document.addEventListener('DOMContentLoaded',async()=>{$('#adminLoginForm')?.addEventListener('submit',submitLogin);$('#adminLogout')?.addEventListener('click',logout);$('#statusFilter')?.addEventListener('change',render);$('#refreshBoard')?.addEventListener('click',load);if(getAuth())await showBoard();else showLogin()});
})();