(()=>{
const SUPA='https://iymhyxheggqsewpczgjl.supabase.co',KEY='sb_publishable_Q8yb_Mw70jDkwld8YGQRRw_h-T5Rau2';
const PRICE={small:27.99,large:37.99,suit:25,express:49.99},LABEL={small:'Small Bag',large:'Large Bag',suit:'Suit Service',express:'Same-Day Express'};
const $=(s,r=document)=>r.querySelector(s),money=n=>'£'+Number(n||0).toFixed(2),today=()=>new Date().toISOString().slice(0,10);
async function post(path,body,headers={}){const r=await fetch(SUPA+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',...headers},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.message||d.msg||d.error_description||d.error||d.hint||'Request failed.');return d}
function saveSession(d){const token=d?.access_token||d?.session?.access_token;if(!token)return;localStorage.setItem('pressed_auth_v2',JSON.stringify({access_token:token,refresh_token:d?.refresh_token||d?.session?.refresh_token||'',user:d.user||d.session?.user||null}));}
function build(form){const g=n=>String(form.get(n)||'').trim(),service=window.PRESSED_SERVICE||'small',shirts=Number(form.get('extraShirts')||0),email=g('email').toLowerCase(),name=g('name');return {email,name,profile:{email,name,phone:g('phone'),address1:g('address1'),address2:g('address2'),postcode:g('postcode').toUpperCase(),accessNotes:g('accessNotes')},booking:{id:crypto.randomUUID(),ref:`PDB-${today().replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,service,serviceLabel:LABEL[service],price:PRICE[service]+((service==='small'||service==='large')?shirts*3:0),name,email,phone:g('phone'),address1:g('address1'),address2:g('address2'),postcode:g('postcode').toUpperCase(),itemCount:Number(form.get('itemCount')||0),extraShirts:shirts,collectionDate:g('collectionDate'),collectionSlot:window.PRESSED_SLOT||'',returnDate:g('returnDate'),returnSlot:g('returnSlot'),accessNotes:g('accessNotes'),instructions:g('instructions')}}}
function confirm(b,msg){const box=$('#confirmation');if(!box)return;box.classList.add('show');[['#confirmRef',b.ref],['#confirmService',b.serviceLabel],['#confirmPrice',money(b.price)],['#confirmWhen',`${b.collectionDate} · ${b.collectionSlot}`],['#confirmAccount',msg]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v});box.scrollIntoView({behavior:'smooth',block:'center'})}
async function handle(form){const fd=new FormData(form),x=build(fd),password=String(fd.get('password')||''),btn=form.querySelector('button[type=submit]');if(!x.booking.collectionSlot)return alert('Please choose an available collection window.');if(password.length<8)return alert('Please use a password of at least 8 characters.');if(x.booking.service==='express'&&(x.booking.itemCount<1||x.booking.itemCount>10||x.booking.collectionDate!==today()))return alert('Same-Day Express is limited to 10 garments and must be collected today.');const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='CREATING ACCOUNT & BOOKING...'}try{let d;try{d=await post('/auth/v1/signup',{email:x.email,password,data:{full_name:x.name,brand:'pressed_db'}})}catch(e){if(/already|registered|exists/i.test(e.message))throw new Error('That email already has a My Presse’d account. Choose “I already have an account” and sign in.');throw e}const u=d.user||d.session?.user;if(!u?.id)throw new Error('Could not create your My Presse’d account. Please try again.');saveSession(d);await post('/rest/v1/rpc/pressed_create_first_booking',{p_user_id:u.id,p_email:x.email,p_profile:x.profile,p_booking:x.booking});localStorage.setItem('pressed_last_email',x.email);localStorage.setItem('pressed_last_ref',x.booking.ref);confirm(x.booking,d.access_token||d.session?.access_token?'Your My Presse’d account and booking are ready.':'Your booking is saved. Check your email to verify your My Presse’d account before your first sign-in.');window.PressedLiveSlots?.refresh?.()}catch(e){const m=e.message||'Could not create your account and booking.';alert(/verify this new My Presse/i.test(m)?'That email may already have a My Presse’d account. Choose “I already have an account” and sign in.':m)}finally{if(btn){btn.disabled=false;btn.textContent=old||'CREATE ACCOUNT & REQUEST BOOKING'}}}
document.addEventListener('submit',e=>{if(e.target?.id!=='bookingForm')return;const mode=window.PRESSED_ACCOUNT_MODE||'new';if(mode!=='new')return;e.preventDefault();e.stopImmediatePropagation();handle(e.target)},true);
})();